### ISSUE TITLE
TP_BE: Add `/images` route

### ISSUE THREAD

**Issue by wijohnst** [wijohnst/tp-express-backend#13]
# TL/DR

Add a new route `/images` and associated `CRUD` endpoints.

## Subtasks

- [ ] Add `routes/images.js` endpoints file
- [ ] Add `models/images.js` to define image schema
- [ ] Add `GET: images/${IMAGE_ID}` endpoint
- [ ] Add `POST: /` endpoint
- [ ] Add `DELETE: images/${IMAGE_ID}` endpoint

## Resources
[TP_EXPRESS_BE _AWS_S3_Integration_Schematic.pdf](https://github.com/wijohnst/tp-express-backend/files/8749937/TP_EXPRESS_BE.%2B.AWS.S3.Integration.-.Page.1.pdf)
